management:
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      maximum-expected-value:
        http.server.requests: 5s
    tags:
      application: micrometer-sample
  endpoints:
    web:
      exposure:
        include: prometheus
server:
  port: 8080

demo:
  base-latency: 10
  client-delay: 10
